name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*.cpp'
      - 'include/**/*.hpp'
      - 'tests/**/*.cpp'
      - 'readme.md'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Install Dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y doxygen graphviz lcov llvm libcxxopts-dev

      - name: Generate Doxygen
        run: doxygen Doxyfile

      - name: Build with coverage
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCOVERAGE=ON
          cmake --build build --target coverage --parallel $(nproc)

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          disable_search: true
          files: build/coverage.info
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@a38818475bb21847788496e9f0fddaa4e84955ba
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/coverage.info

      - name: Clean build
        run: rm -rf build/

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4